const data = [
  {
    id: 1,
    name: 'Harry Potter & The Philosopher\'s Stone',
    description: 'Harry Potter & The Philosopher\'s Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling\'s debut novel, it follows Harry Potter, a young wizard, in the wizarding world of Hogwarts, where he learns the truth about his parents\' deaths and the mysterious events surrounding him.',
    image: 'https://images-na.ssl-images-amazon.com/images/I/910ityjoncL.jpg',
    genre: 'Fiction',
    author: 'J.K Rowling',
  },
  {
    id: 2,
    name: 'Harry Potter & The Chamber of Secrets',
    description: 'Harry Potter & The Chamber of Secrets is a fantasy novel written by British author J. K. Rowling. The second novel in the Harry Potter series, it follows Harry Potter, a young wizard, in the wizarding world of Hogwarts, where he discovers the truth about his parents\' deaths and the mysterious events surrounding him.',
    image: 'https://images-na.ssl-images-amazon.com/images/I/91HHqVTAJQL.jpg',
    genre: 'Fiction',
    author: 'J.K Rowling',
  },
  {
    id: 3,
    name: 'Harry Potter & The Prisoner of Azkaban',
    description: 'Harry Potter & The Prisoner of Azkaban is a fantasy novel written by British author J. K. Rowling. The third novel in the Harry Potter series, it follows Harry Potter, a young wizard, in the wizarding world of Hogwarts, where he discovers the truth about his parents\' deaths and the mysterious events surrounding him.',
    image: 'https://images-na.ssl-images-amazon.com/images/I/81EbEWM54ML.jpg',
    genre: 'Fiction',
    author: 'J.K Rowling',
  },
  {
    id: 4,
    name: 'Harry Potter & The Goblet of Fire',
    description: 'Harry Potter & The Goblet of Fire is a fantasy novel written by British author J. K. Rowling. The fourth novel in the Harry Potter series, it follows Harry Potter, a young wizard, in the wizarding world of Hogwarts, where he discovers the truth about his parents\' deaths and the mysterious events surrounding him.',
    image: 'https://images-na.ssl-images-amazon.com/images/I/81t2CVWEsUL.jpg',
    genre: 'Fiction',
    author: 'J.K Rowling',
  },
  {
    id: 5,
    name: 'Harry Potter & The Order of the Phoenix',
    description: 'Harry Potter & The Order of the Phoenix is a fantasy novel written by British author J. K. Rowling. The fifth novel in the Harry Potter series, it follows Harry Potter, a young wizard, in the wizarding world of Hogwarts, where he discovers the truth about his parents\' deaths and the mysterious events surrounding him.',
    image: 'https://images-na.ssl-images-amazon.com/images/I/91t5-Juqt9L.jpg',
    genre: 'Fiction',
    author: 'J.K Rowling',
  },
  {
    id: 6,
    name: 'Harry Potter & The Half-Blood Prince',
    description: 'Harry Potter & The Half-Blood Prince is a fantasy novel written by British author J. K. Rowling. The sixth novel in the Harry Potter series, it follows Harry Potter, a young wizard, in the wizarding world of Hogwarts, where he discovers the truth about his parents\' deaths and the mysterious events surrounding him.',
    image: 'https://images-na.ssl-images-amazon.com/images/I/51WvQzucOqL._SX314_BO1,204,203,200_.jpg',
    genre: 'Fiction',
    author: 'J.K Rowling',
  },
  {
    id: 7,
    name: 'Harry Potter & The Deathly Hallows',
    description: 'Harry Potter & The Deathly Hallows is a fantasy novel written by British author J. K. Rowling. The seventh and final novel in the Harry Potter series, it follows Harry Potter, a young wizard, in the wizarding world of Hogwarts, where he discovers the truth about his parents\' deaths and the mysterious events surrounding him.',
    image: 'https://images-na.ssl-images-amazon.com/images/I/51jyI6lYi1L._SX342_BO1,204,203,200_.jpg',
    genre: 'Fiction',
    author: 'J.K Rowling',
  },
  {
    id: 8,
    name: 'Harry Potter & The Cursed Child',
    description: 'Harry Potter & The Cursed Child is a fantasy novel written by British author J. K. Rowling. The eighth novel in the Harry Potter series, it follows Albus Severus Potter, a young wizard, in the wizarding world of Hogwarts, where he discovers that he is the heir to a magical object that has been stolen from the wizarding world.',
    image: 'https://images-na.ssl-images-amazon.com/images/I/81hV7BRj8vL.jpg',
    genre: 'Fiction',
    author: 'J.K Rowling',
  },
  {
    id: 9,
    name: 'Fantastic Beasts and Where to Find Them',
    description: 'Fantastic Beasts and Where to Find Them is a fantasy novel written by British author J. K. Rowling. The first novel in the Fantastic Beasts series, it follows Newt Scamander, a young wizard who discovers a mysterious place known as the Magical Congress of the United States of America.',
    image: 'https://images-na.ssl-images-amazon.com/images/I/91Aufge9S1L.jpg',
    genre: 'Fiction',
    author: 'J.K Rowling',
  },
  {
    id: 10,
    name: 'Fanstastic Beasts and The Crimes of Grindelwald',
    description: 'Fantastic Beasts and The Crimes of Grindelwald is a fantasy novel written by British author J. K. Rowling. The second novel in the Fantastic Beasts series, it follows Newt Scamander, a wizard and former employee of Grindelwald, who is accused of killing Lord Voldemort, who had been a Dark wizard for many years.',
    image: 'https://images-na.ssl-images-amazon.com/images/I/61CDJpXD3cL._SX340_BO1,204,203,200_.jpg',
    genre: 'Fiction',
    author: 'J.K Rowling',
  },
];

export default data;
